### ISSUE TITLE
before_all(CORS setup) is not applied to OPTIONS request ?

### ISSUE THREAD

**Issue by joaumg** [kemalcr/kemal#420]
### Description

Doing a CORS request from foo.com to bar.com in a POST endpoint fails, even with the following code:

```
before_all do |env|
  env.response.headers["Access-Control-Allow-Origin"] = "*"
end

post "/x" do |env|
  # some code
end
```

GET requests do work as intended.

What is odd, is that the OPTIONS request returns a 404... in fact doing a curl request returns the same

    Request URL: http://.../x
    Request Method: OPTIONS
    Status Code: 404 Not Found

**Expected behavior:** The endpoint should be resolved.

**Actual behavior:** OPTIONS get's a 404, POST isn't done.

**Reproduces how often:** 100%

### Versions

Crystal 0.23.1 [e2a1389] (2017-07-13) LLVM 3.8.1
Kemal 0.21.0
Debian 9 (stretch)

### Edit

Doing a curl request:

    curl -X POST http://.../x works, so the problem is really the OPTIONS verb.

Looking at Kemal's source code, there is indeed a OPTIONS method:

https://github.com/kemalcr/kemal/blob/210e2c0801294e1d013d4120e3b71292e39d4f72/src/kemal/dsl.cr#L9

Should this be auto-created for every POST request ?
Or is up to the dev to do it for each POST method he creates ? If so what should be "sent back?" besides the CORS headers?

**Comment by joaumg** [comment]
Ok. If I edit the `before_all` to be:

```ruby
before_all do |env|
  env.response.headers["Access-Control-Allow-Origin"] = "*"
  env.response.headers["Access-Control-Allow-Methods"] = "GET, HEAD, POST, PUT"
  env.response.headers["Access-Control-Allow-Headers"] = "Content-Type, Accept, Origin, 
Authorization"
  env.response.headers["Access-Control-Max-Age"] = "86400"
end
```

and create a OPTIONS endpoint:

```ruby
options "/x" do |env|
end
```

It works. However it's still annoying to create an options for every post... is there a way to macro it ?

**Comment by sdogruyol** [comment]
CORS is different, please check Kemal CORS recipe http://kemalcr.com/cookbook/cors/

**Comment by joaumg** [comment]
Sorry. But it didn't seem that you read the issue AT ALL.

Or maybe I'm misunderstanding `static_headers`... (at least from the referenced cookbook it's for *STATIC* files, not POST requests...)

What is being discussed here is if I do a POST endpoint, and I want it to accept CORS, I'm obliged to do a blank `options` before such `post`, or the browser (Chrome, Firefox, whatever) will fail on [preflight](https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request).

This also feels like an oversight from Kemal's devs, since for EVERY POST ENDPOINT which could be CORS related the dev (Kemal user) would have to do a blank `option`. Just imagine a site which has a json backend api on top of kemal, for example `api.example.com` and the main site is `example.com`... you get the picture ?

**Comment by straight-shoota** [comment]
Yes, `static_headers` is only for static files served by `Kemal::StaticFileHandler`.

If I understand you correctly, you're suggesting to automatically provide an `OPTIONS` method for every `POST` endpoint used with CORS.

I think it makes sense to provide an easy and generalized means to achieve this, but it needs to be determined how this should be implemented.
Please note, that the OPTIONS preflight check is not limited to `POST` method. In fact, `POST` is considered a *simple method* and can be used without preflight check if used with a *simple header* -
which means a content type `application/x-www-form-urlencoded`, `multipart/form-data`, or `text/plain` (see [W3C Recommendation](https://www.w3.org/TR/cors/#terminology)).
Every non-simple method (any except `GET`, `HEAD`, `POST`) requires a preflight check, so this is not limited to `POST`.

One solution, advocated among others by [sinatra-cross_origin](https://github.com/britg/sinatra-cross_origin) is to use a wildcard matcher for options endpoint, so that each and every `OPTIONS` endpoint returns CORS headers. This is however not ideal, because it marks *all* paths as CORS-enabled which might not be intended.

```crystal
options "*" do |env|
  env.response.headers["Allow"] = "HEAD,GET,PUT,POST,DELETE,OPTIONS"
  env.response.headers["Access-Control-Allow-Headers"] = "X-Requested-With, X-HTTP-Method-Override, Content-Type, Cache-Control, Accept"
 
  halt 200
end
```

It would be nice if we could offer a better way to define an automatic OPTIONS endpoint directly with the non-simple method endpoint, like this:
```crystal
post "/x", cors: true do |env|
end
# Or
post "/x", options: true do |env|
end
```
Instead of `true` this could also allow for detailed header configuration.
This is similar to what [expressjs](https://github.com/expressjs/cors#enabling-cors-pre-flight) does.

**Comment by joaumg** [comment]
> One solution, advocated among others by sinatra-cross_origin is to use a wildcard matcher for options endpoint, so that each and every OPTIONS endpoint returns CORS headers. This is however not ideal, because it marks all paths as CORS-enabled which might not be intended.

This is perfect for our use case (JSON API Backend).

About the preflight... yes, we can pass it sending JSON with a Content-Type of `text/plain`... but it still seems like a hack.

However, I agree that better options could be used... one of which, options could accept an array of paths?

```ruby
options ["/foo", "/bar"] do |env|
  env.response.headers["Allow"] = "HEAD,GET,PUT,POST,DELETE,OPTIONS"
  env.response.headers["Access-Control-Allow-Headers"] = "X-Requested-With, X-HTTP-Method-Override, Content-Type, Cache-Control, Accept"
 
  halt 200
end
```

Also another option would be use meta programming, but I didn't get too far using macros...
Something like (at least this works with C/C++ family):

```cpp
#define post(path) options(path) { |env| env.response ... } post(path)
```

But I don't know how to write this properly with Crystal yet.

@sdogruyol, what are your thoughts ?

**Comment by straight-shoota** [comment]
If the match-all wildcard suits your usecase, all the better.

But I don't like the idea of centrally defining all options routes from an array. This should be setup at together with the POST (etc.) routes which need a preflight check.

This could be done with a route-specific flag or application wide, like `Kemal.config.auto_cors_options = true`.
