### ISSUE TITLE
multipart/form-data parses wrong and EOF error at <input multiple>

### ISSUE THREAD

**Issue by BenDietze** [kemalcr/kemal#455]
Using this code

```crystal
require "kemal"

get "/" do
  <<-HTML
  <!DOCTYPE html>
  <html lang="de">
  <head>
      <meta charset="utf-8">
  </head>
  <body>
      <form method="post" action="upload" enctype="multipart/form-data">
          <input name="image1" type="file">
          <button>SEND</button>
      </form>
  </body>
  </html>
  HTML
end

post "/upload" do |env|
  env.params.files.each_value do |file|
    filename = file.filename
    if !filename.is_a?(String)
      p "No filename included in upload"
    else
      file_path = ::File.join [Kemal.config.public_folder, "uploads/", filename]
      File.open(file_path, "w") do |f|
        IO.copy(file.tmpfile, f)
      end
      "Upload ok"
    end
  end
end

Kemal.run
```

uploading **one file** is fully ok.

Uploading **multiple** files due

```bash
curl -F "image1=@1.png" -F "image2=@2.png" -F "image3=@3.png" -F "image4=@4.png" 127.0.0.1:3000/upload
```

all parsing is ok again, all 4 files were handled correctly:

![image](https://user-images.githubusercontent.com/39699022/41620166-2e89b53a-7409-11e8-9ceb-80843ebecc4f.png)

But handling multiple file upload from browser by changing `<input name="image1" type="file">` to `<input name="image1" type="file" multiple>`

does **not** handle the images correctly - only _the last one_ ist saved:

![image](https://user-images.githubusercontent.com/39699022/41620303-9149c9c6-7409-11e8-823e-8fa219e44618.png)

If i do `pp file` in `env.params.files.each_value do |file|` then it ouputs simply:

```bash
Kemal::FileUpload(
 @creation_time=nil,
 @filename="4.png",
 @headers=
  HTTP::Headers{"Content-Disposition" =>
    "form-data; name=\"image1\"; filename=\"4.png\"",
   "Content-Type" => "image/png"},
 @modification_time=nil,
 @read_time=nil,
 @size=nil,
 @tmpfile=#<File:/tmp/.NsoCU9>)
2018-06-19 22:23:51 +02:00 200 POST /upload 9.03ms
```

**Note:** `"form-data; name=\"image1\"; filename=\"4.png\"",`

So, i have an error while parsing `multipart/form-data` from `<input name="NAME" type="file" multiple>`: it seems, all files were handled as `name="image1"` - the last one at least becomes `"image1"`

Looking at the raw request data shows, that `"image1"` (_bad name_; better `"images"`) should be an array of images - look at original code from firefox: (this selected is _complete_ body, but excluding `\r\n` to Line 42 - cannot select it)

![image](https://user-images.githubusercontent.com/39699022/41620589-73c7ea08-740a-11e8-8cd3-f221a8df25a3.png)

_**Note:** the image data of all 4 images above is exactly the same and very small; i created just 4 dummy images with 10x10px to reduce the request to a readable value._

**Note:** _all 4 images were handled as_ `name="image1"` _by browser_ (tested with _chrome_ and _firefox_)

I have tried this on Windows WSL and Ubuntu, with **kemal 0.23.0** and **Crystal 0.25.0**

Parsing fails also, when changing `post` to:

```crystal
post "/upload" do |env|
  HTTP::Multipart.parse(env.request) do |headers, io|
    # ... do something
  end
end
```

Then happens:

![image](https://user-images.githubusercontent.com/39699022/41620914-6c417546-740b-11e8-843e-b8bd68eec2ab.png)

same on both, Windows WSL and Ubuntu, but here **kemal** is showing Error 500.

I have tried several images; this dummys are just for showing. For me, _multiple file upload_ via `multiple` (_one click_; or correct parsing of multipart/form-data in all cases) is a must-have, so i hope this issue could be solved soon :)

**Comment by straight-shoota** [comment]
This is just cause by `ParamParser` storing uploads in `@files[upload.name]`, that's why the latest upload with the same name will overwrite the previous ones.

I'm not sure about the error 500 but that's probably because the request IO is already consumed when you call `HTTP::Multipart.parse(env.request)`, so it's basically trying to read a multipart message from an empty IO.

**Comment by BenDietze** [comment]
Thank you for quick answer 👍 

The second, Error 500: very good to know :) (I tried just)

The first one: can you correct it to be useable with `<input multiple>` tag? This were very useful, because it's HTML5 :) https://www.w3schools.com/tags/att_input_multiple.asp (otherwise all users must click each `<input name="image1">`, `<input name="image2">`, `<input name="image3">` - no multiple choice with one button / click)

**Comment by straight-shoota** [comment]
Unfortunately, I don't think this can't be simply fixed. `ParamParser` is designed to have exactly one file per upload name. This can't be changed without introducing a breaking change or making the API more complicated.

I'd rather suggest to think about the general API design of `ParamParser`. Right now, it always consumes all multipart parts and stores the data in tempfiles (if a filename is present), when `#body` is accessed. And this happens in *every* `POST` request handled by Kemal (even before the specific handlers are called) because `Context#route_lookup` checks for method override if the request body has a `_method` field. This happens before the route handler is able to determine if such a request with attached formdata is valid. If the user isn't authorized, for example, the request body doesn't even need to be consumed. But it is automatically stored on disk. This can be inefficient and potentially even poses as a DoS thread.

Maybe it would make more sense to make the formdata handling even more flexible. Sometimes, the uploaded data isn't supposed to be saved to disk at all, but rather directly processed or directed to a remote service. Automatically storing all (named) files to disk can be a unnecessary overhead. 

Of course, one could just use `HTTP::FormData` or `HTTP:Multipart` directly for such customization. The example with `HTTP::Multipart.parse(env.request)` should actually work (hadn't the request already been consumed by the above mentioned method override check). This needs to be fixed to provide way to apply a workaround using lower-level methods.

The rest is largely a question if Kemal should provide an easy, automatic file upload handling which will maybe require one or two extra steps for simple applications, or a more sophisticated approach supporting `<input multiple>` as well as maybe more flexible access methods for fine-grained control of upload handling.

**Comment by BenDietze** [comment]
@straight-shoota, thanks for your great initiate to this :+1:

When kemal starts it maybe in mind it´s for ease of use, but kemal stays as a professional shard, and my first time as i saw `@tmpfile=#<File:/tmp/.NsoCU9>)` in `Kemal::FileUpload` i was a little bit surprised.

Using kemal in a professional high-traffic system seems to be not the very best value for massive post requests due to this _tempfile-ing_; but this is indeed a bigger change.

Do you mean, as workaround, it isn´t possible to append something like `"(Number)"` to `upload.name` in `@files[upload.name] = FileUpload.new(upload: upload)`?

So, if we append an increasing number, it could became like:

```crystal
{
    "image1" => Kemal::FileUpload,
    "image1(2)" => Kemal::FileUpload,
    "image1(3)" => Kemal::FileUpload,
    "image1(4)" => Kemal::FileUpload
}
```

(in this example starting with `2` and because `@files.has_key?(upload.name)` is `true`) or more generally

```crystal
{
    "images(1)" => Kemal::FileUpload,
    "images(2)" => Kemal::FileUpload,
    "images(3)" => Kemal::FileUpload,
    "images(4)" => Kemal::FileUpload
}
```

If there were only one file, like

```crystal
{"files(1)" => Kemal::FileUpload}
```
or
```crystal
{"upload(1)" => Kemal::FileUpload}
```

this will not become ugly - but one will die: _as is,_ is not ready for `<input multiple>` due to overwrite or as an extending workaround with an appending String, which can be easily catched and dropped. The String could be `(x)` or `_x` or whatever; catching this will be lovelier as lost the upload.

One can decline it as _workaround_ or _simply appending to the name generally_ - if i had this in the doc i would not think to much about it - it seems more like a cosmetic decission.

But, in my opinion, the first one could be the best fit:

```crystal
{
    "images" => Kemal::FileUpload,
    "images(2)" => Kemal::FileUpload,
    "images(3)" => Kemal::FileUpload,
    "images(4)" => Kemal::FileUpload
}
```
seems to be good to me and fits better for one-file-uploads, as would stay as:

```crystal
{"upload" => Kemal::FileUpload}
```

What do you think? Would this be possible?

**Comment by straight-shoota** [comment]
This would be possible, but I don't think it makes sense. If there needs to be an urgent workaround, I'd refactor `@files` to hold a list of upload items instead of doing potentially troublesome and not-that-easy-to-use key renaming. If you apply this as a monkey patch to your code, you can leave it at that and don't worry about breaking change.

Introducing this as a fix into kemal master would require some more effort to avoid that. I don't think such a fix makes sense and would rather take a look at the greater design, as detailed in my previous post.

**Comment by RX14** [comment]
I'd make sure people can use far stdlib `HTTP::FormData`, because it's a well thought out interface, then I'd modify it to either be a `Hash(String, Array(FileUpload))`, or just an `Array(FileUpload)`. making a breaking change is fine in crystal, why wouldn't it be fine in kemal?

**Comment by straight-shoota** [comment]
Yes, it's fine to have a breaking change. But I'd only break it if I know what the supposed end result looks like. 

In fact, I'm even arguing for a bigger breaking change. As mentioned above, the current way kemal handles form data automatically has issues. If that gets changed, it will also change the API to access file uploads.

**Comment by straight-shoota** [comment]
I'd prefer to got that road directly instead of adding a small fix for one specific issue which doesn't solve the general problem.

**Comment by BenDietze** [comment]
Great benefit for me - thanks 👍 

@straight-shoota Yes, refactoring `@files` would be one of my thoughts, but then you will have an API-change because `env.params.files` would be changed - as of now it is `Hash(String, Kemal::FileUpload)`. And you preferered not to change.

Ok, let´s go with kemal 🥇
