### ISSUE TITLE
Version constant enhancement?

### ISSUE THREAD

**Issue by lebogan** [kemalcr/kemal#469]
Is it possible to have a constant like Crystal::VERSION called Kemal::VERSION added during the next development cycle?
Thank you.

**Comment by straight-shoota** [comment]
Why don't you just submit a PR for that? =)

**Comment by lebogan** [comment]
Got it.=o

**Comment by lebogan** [comment]
Okay, @straight-shoota , I did a pull request and ended up causing an issue due to having a literal "0.23.0" in my test (at least, I think that's what the issue was). That was a rookie mistake as pointed out by others. In attempting to correct my error, I modified my test to check for a empty string. Submitting a new PR to fix my original causes a  #conflict that I am having a hard time resolving. Any help and reviews are greatly appreciated.

Note: I really am a rookie. Would it have been better to add a version.cr file with my additions?

**Comment by straight-shoota** [comment]
Yeah #476 is fine I think. It's just that this PR contains the same changes as #471 (and an additional commit) and it is based on the state before #471 was merged. Now that #471 has been merged, this can't be applied.

You can resolve this either in the Github UI, there should be a link to resolve conflicts at the bottom of the PR page.
Or, on the command line you need to rebase on the current master branch (replace `upstream` with your name for the crystal-lang/crystal repo):
```
git fetch upstream master
git rebase FETCH_HEAD
```` 
During the rebase process, it will probably tell you there are commits which don't change anything because it is already in master. You can just run `git rebase --skip` in that case, it will skip the current commit. If it tells you there are conflicts in a file, open the file and edit the marked locations (it shows two variants of conflicting content). Then just add the file and run `git rebase --continue`.

When the rebase has finished, you need to push it back to Github doing a force push:
```
git push --force
```

**Comment by lebogan** [comment]
Okay. I think I have managed to correct my previous mistakes re #471 ans #476. Test have passed and the literal string has been removed from the test, config_spec.cr.

Please, advise if there is anything else I need to do or if it maybe makes to add a version file to accomplish what I want to do.

Thanks to all who set me straight!

**Comment by sdogruyol** [comment]
Thanks @lebogan :+1:
