### ISSUE TITLE
Resources that exist but not registered to the HTTP method being used are returning a 404

### ISSUE THREAD

**Issue by drum445** [kemalcr/kemal#497]
### Description

When a route is registered such as:
```crystal
module CrystalRest
  get "/test" do |env|
    {"message" => "hello world"}.to_json
  end
end
```
When performing non-get methods to "/test" it should return a 405 not allowed. As the resource exists a 404 is the incorrect response

Thanks

**Comment by codenoid** [comment]
get "/test"
post "/test"
get "/test/:part"

when i access `get "/test/:part"` kemal access -> `post "/test"`

really weird huh ?, i found this about 14days ago

**Comment by sdogruyol** [comment]
@codenoid I can't reproduce this with the following

```
require "kemal"

get "/test" do
"GET"
end

post "/test" do
    "POST"
end

get "/test/:part" do
    "part"
end

Kemal.run
```

what's your Kemal version? Please provide a reproducible snippet.

**Comment by sdogruyol** [comment]
Thank you for the issue @drum445. I'd like to keep Kemal as simple as possible. I think adding this feature will only make Kemal more complex yet not providing any visible benefit.

**Comment by drum445** [comment]
Hi @sdogruyol, it's not that the route can't be registered, it's that Kemal is returning a 404 incorrectly.
If a resource exists, let's use customer for example and method to that resource should never return a 404, but a 405 if the method is in use.

```crystal
require "kemal"

get "/customer" do
  "GET"
end

# Any other request method to /customer should be returning a 405

Kemal.run
```

This is how many other rest frameworks behave and is the standard, i.e. Python Flask, Go Gorilla.

Thanks mate

**Comment by straight-shoota** [comment]
Returning 404 is not strictly incorrect. A request to a resource that is declared with a different method *could* return 405 and that would probably be *better*. I am not aware that the HTTP specification enforces a strict requirement for that.

Some frameworks like Flask (I don't know about Gorilla) have a data model that lets them easily determine if a route to a resource is defined for *any* HTTP verb. Thus, it's really easy to return 405 in that case.
In frameworks like Kemal and it's conceptual role model Sinatra it would be much more difficult to determine if a resource is defined at all. With the current data model this would essentially mean resolving a route for *all* other verbs on any request that doesn't resolve for the requested verb. And still that wouldn't even be reliable because when a route resolves, doesn't mean the resource exists. The handler could still return a 404 for the given resource.

I don't think this can be implemented with Kemal. It primary focus is not being 100% REST compliant (whatever that would mean, anyway).

**Comment by drum445** [comment]
@straight-shoota, ok, seems we'll leave this for now. Would be useful to have some middleware on the kemal site to add this though as it is something I can see people wanting.

Cheers
