### ISSUE TITLE
Any chance render could just use the default url for a view template?

### ISSUE THREAD

**Issue by u89012** [kemalcr/kemal#536]
New here and loving Kemal so far! Thank you for all the hard work. I've a quick question -- I'm trying to port an old Sinatra script (for performance reasons) and I've a thousand or so routes and having to specify the template file over and over when calling render is getting tiring, is there a way to have render just pick up a template based on the current url? Like so:

```
get("/foo/bar/baz"){|env|
    render #would look for views/foo/bar/baz.ecr
}
```

If this can't be done without breaking a lot of things, what would a similar function/macro look like, cuz I can't seem to be able to write one.

**Comment by rdp** [comment]
that would be interesting, or do it for a whole directory or something default-y...

**Comment by wontruefree** [comment]
Would you ever not want to render something?
Seems like if you dont have render in there it should just call render with a default automatically.

**Comment by u89012** [comment]
@wontruefree Well, if that works, sure! And that's the approach Ramaze uses -- if there's a template for the given route, render it or just render the return value of the route. There's always halt if you don't want to render anything (at least that's what I've used).

**Comment by straight-shoota** [comment]
> Would you ever not want to render something?
> Seems like if you dont have render in there it should just call render with a default automatically.

Of course. HTTP responses don't need to have a body at all.

I don't think kemal should render anything automatically.

Maybe an `render` call with implicit template path could be possible. But it's not trivial, because the render method somehow needs to know the request path, so it would either have to be something like `render(env)` or the request path must be passes in some other way.

I doubt that's really much useful, though. Instead, I'd rather recommend to use a custom handler method for this. That gives you all the freedom to do exactly what you want.
For example:
```cr
def custom_get(path : String, &block : HTTP::Server::Context -> _)
  get(path) do |context|
    block.call
    render path
  end
end
```

**Comment by sdogruyol** [comment]
I'm on the same page as @straight-shoota here. Using a custom handler would do the trick 👍
