### ISSUE TITLE
Exception hangs process on FreeBSD

### ISSUE THREAD

**Issue by yujiri8** [kemalcr/kemal#589]
```crystal
require "kemal"

get "/" do |env|
 raise "error"
end

Kemal.run
```

Using the master branch of Kemal and Crystal 0.35.1. On Linux, this works fine: Kemal dumps a stack trace and an error page is returned to the client. On FreeBSD, the process hangs when the exception is raised. It becomes impossible to kill except via SIGKILL. CPU and memory use do not increase. And according to SIGINFO output, the process state is `uwrlck`.

This is the full output of `crystal version` on the FreeBSD server that experiences the problem:

```
Crystal 0.35.1 ()

LLVM: 10.0.1
Default target: x86_64-portbld-freebsd12.1
```

The server is running FreeBSD 12.1-RELEASE-p10.

**Comment by yujiri8** [comment]
Starting to feel like putting a bounty on this. I'm not sure what to do

**Comment by bitmand** [comment]
@yujiri8 I did a bit of testing -  I have no idea if all this helps or not, but hope it does :) (and feel free to let me know, if I can help/test this in any other way)

### Versions

    FreeBSD 12.1-RELEASE-p11
    Crystal 0.35.1 ()
    Shards 0.12.0 (2020-12-05)
    OpenSSL Base: OpenSSL 1.1.1d-freebsd  10 Sep 2019
    OpenSSL Ports: OpenSSL 1.1.1h  22 Sep 2020

### Setup

Installed packages:

    pkg install crystal shards git openssl

openssl package due to this error: https://github.com/crystal-lang/crystal/issues/7244

Created crystal app:

    crystal init app kemal-app

Added this to `shards.yml` and ran `shards install`:

    dependencies:
      kemal:
        github: kemalcr/kemal

### Test with raise error

Created `test-raise-error.cr`:

    require "kemal"
    get "/" do |env|
      raise "error"
    end
    Kemal.run

Testing with a user running the app and root running dwatch:

    lasse@dev:~/kemal-app % rm -fr ../.cache/

    root@dev:~ # dwatch -u lasse execve
    INFO Watching 'syscall:freebsd:execve:entry' ...
    INFO Filtering user: lasse

    lasse@dev:~/kemal-app % crystal run test-raise-error.cr

Full dwatch output during startup: https://gist.github.com/bitmand/6b0a2c39f31f231bb7a061f3b1aeeeca

Near the end of the dwatch output, kemal writes to the console:

    [development] Kemal is ready to lead at http://0.0.0.0:3000

There is no more output from dwatch from this point on.

If I make a `GET /` request, I can see the tcp connection is created, but no output is returned:

    Proto Recv-Q Send-Q Local Address          Foreign Address        (state)
    tcp4       0      0 192.168.0.16.3000      192.168.0.40.53622     ESTABLISHED
    tcp4       0      0 *.3000                 *.*                    LISTEN

### Terminating the unresponsive kemal app

I have noticed 2 different patterns. At this point there is 2 processes running:

    lasse   23732   4.0  9.8 486280 407132  2  S+   12:40       0:12.52 crystal run test-raise-error.cr
    lasse   23789   0.0  0.3  64716  14092  2  S+   12:40       0:00.04 /home/lasse/.cache/crystal/crystal-run-test-raise-error.tmp

If I try and terminate the kemal app the usual way:

1. CTRL+C in the console: nothing happens.
2. Kill both processes with: `kill 23732 23789`
3. Process 23732 dies, but 23789 does not (23789 can be killed with `kill -9`)

If I restart the test, make the `GET /` request which still fails, but this time don't try and terminate the kemal app:

1. Do NOT hit CTRL+C in the console!
2. Kill both processes with: `kill 23732 23789`
3. Both processes dies and no process hangs.

It might just be a symptom, just though I should mention it.

### Observation

I also tested a kemal app without the `raise "error"` and it worked as expected (see test at bottom).

Comparing the dwatch output from `test-hello.cr` and `test-raise-error.cr` this seems to be the only difference:

    2020 Dec 13 12:18:49 1001.1001 tcsh[21936]: crystal run test-hello.cr
    ..
    2020 Dec 13 12:19:00 1001.1001 cc[23512]: ld.lld
    2020 Dec 13 12:19:00 1001.1001 cc[23482]: /home/lasse/.cache/crystal/usr-local-lib-crystal-ecr-process.cr/macro_run /usr/home/lasse/kemal-app/lib/exception_page/src/exception_page/exception_page.ecr __io__
    2020 Dec 13 12:19:00 1001.1001 crystal[23482]: /home/lasse/.cache/crystal/usr-local-lib-crystal-ecr-process.cr/macro_run /usr/local/lib/crystal/http/server/handlers/static_file_handler.html __io__
    2020 Dec 13 12:19:04 1001.1001 crystal[23482]: /usr/local/bin/pkg-config z
    ..
    2020 Dec 13 12:19:04 1001.1001 crystal[23482]: /usr/local/bin/pkg-config pthread
    2020 Dec 13 12:19:05 1001.1001 sh[23534]: pkg-config --libs --silence-errors libssl

vs:

    2020 Dec 13 12:35:30 1001.1001 tcsh[21936]: crystal run test-raise-error.cr
    ..
    2020 Dec 13 12:35:41 1001.1001 cc[23642]: ld.lld
    2020 Dec 13 12:35:41 1001.1001 crystal[23612]: /home/lasse/.cache/crystal/usr-local-lib-crystal-ecr-process.cr/macro_run /usr/home/lasse/kemal-app/lib/exception_page/src/exception_page/exception_page.ecr __io__
    2020 Dec 13 12:35:41 1001.1001 crystal[23612]: /home/lasse/.cache/crystal/usr-local-lib-crystal-ecr-process.cr/macro_run /usr/local/lib/crystal/http/server/handlers/static_file_handler.html __io__
    2020 Dec 13 12:35:45 1001.1001 crystal[23612]: /usr/local/bin/pkg-config z
    ..
    2020 Dec 13 12:35:46 1001.1001 crystal[23612]: /usr/local/bin/pkg-config pthread
    2020 Dec 13 12:35:46 1001.1001 crystal[23612]: sh
    2020 Dec 13 12:35:46 1001.1001 sh[23664]: pkg-config --libs --silence-errors libssl
    ..

### Test without raise

Created `test-hello.cr`:

    require "kemal"
    get "/" do |env|
      "Hello"
    end
    Kemal.run

Testing with a user running the app and root running dwatch:

    lasse@dev:~/kemal-app % rm -fr ../.cache/

    root@dev:~ # dwatch -u lasse execve
    INFO Watching 'syscall:freebsd:execve:entry' ...
    INFO Filtering user: lasse

    lasse@dev:~/kemal-app % crystal run test-hello.cr

Full dwatch output during startup: https://gist.github.com/bitmand/9fb53962b7e9d54e7b28dace382a0328

Near the end of the dwatch output, kemal writes to the console:

    [development] Kemal is ready to lead at http://0.0.0.0:3000

There is no more output from dwatch from this point on.

I can make a `GET /` request and receive the response `Hello`:

    2020-12-13 12:20:05 UTC 200 GET / 40.51µs

and I can make Kemal take a rest:

    ^CKemal is going to take a rest!

Everything looks good.

**Comment by yujiri8** [comment]
Wow, that's a deep investigation! I appreciate the effort. To make sure I understand, you didn't find a way to make the server keep responding when it raises an exception?

**Comment by bitmand** [comment]
@yujiri8 unfortunately no :( I was trying to get a trace from when the exception happens, but didn't manage to (primarily due to my lack of experience with dtrace). I'll try again in a day or two and report back.

**Comment by bitmand** [comment]
@yujiri8 just a quick update, I'm not sure the root cause is kemal related and I'm considering opening a separate bug over at https://github.com/crystal-lang/crystal/issues 

On FreeBSD the `raise "error"` hangs, even without kemal:

    % cat raise-error.cr
    puts "hi"
    raise "error"

    % crystal raise-error.cr
    hi
    Unhandled exception: error (Exception)

...and the process hangs (I might add that a simple `kill 32811 32830` works as expected and both processes is terminated).

Processes:

    % ps aux | grep crystal
    lasse   32835   0.0  4.9 242460 202644  1  S+   09:08       0:00.99 crystal raise-error.cr
    lasse   32854   0.0  0.2  34552   9000  1  I+   09:08       0:00.04 /home/lasse/.cache/crystal/crystal-run-r

Process states:

      PID USERNAME    THR PRI NICE   SIZE    RES STATE    C   TIME    WCPU COMMAND
    32835 lasse         4  25    0   245M   198M kqread   1   0:01   0.00% crystal
    32854 lasse         4  52    0    34M  9000K uwrlck   2   0:00   0.00% crystal-run-raise-e

On Linux for comparison: (although running Crystal 0.35.0 here vs 0.35.1 on FreeBSD)
```
$ lsb_release -d
Description:    Ubuntu 18.04.5 LTS
$ crystal --version
Crystal 0.35.0 [3c48f311f] (2020-06-09)

LLVM: 8.0.0
Default target: x86_64-unknown-linux-gnu
```
```
$ cat raise-error.cr
puts "hi"
raise "error"
```
```
$ crystal raise-error.cr
hi
Unhandled exception: error (Exception)
  from raise-error.cr:2:1 in '__crystal_main'
  from apps/crystal/crystal/crystal-0.35.0-1/share/crystal/src/crystal/main.cr:105:5 in 'main_user_code'
  from apps/crystal/crystal/crystal-0.35.0-1/share/crystal/src/crystal/main.cr:91:7 in 'main'
  from apps/crystal/crystal/crystal-0.35.0-1/share/crystal/src/crystal/main.cr:114:3 in 'main'
  from __libc_start_main
  from _start
  from ???
```

...and process terminates as expected.

**Comment by yujiri8** [comment]
NANI?!?

Well. I guess we can close this now.
